name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.Docker_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Dcoker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: ashutosh435/money-minded-wallet:latest 

    - name: Verify Pushed Image
      run: docker pull ashutosh435/money-minded-wallet:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker system prune --all --force || true
          sudo docker pull ashutosh435/money-minded-wallet:latest
          sudo docker run -e DATABASE_URL ${{ SECRETS.DATABASE_URL }} -d --name money-minded-wallet -p 3005:3000 ashutosh435/money-minded-wallet:latest
